### ISSUE TITLE
Request failed 403 forbidden

### ISSUE THREAD

**Issue by sorodrigo** [GoogleCloudPlatform/artifact-registry-npm-tools#21]
We're getting a 403 when installing packages, after having setup the correct token. After many trial and error we noticed that while `gcloud auth login` doesn't work, `gcloud auth application-default login` does.

This doesn't happen to all users though, for me **version 310.0.0** `gcloud auth login` works fine, but for other users with later versions it doesn't.

**Comment by lindsayismith** [comment]
Hi Rogrigo, thanks for the feedback.

The auth library first tries the Application Default Credentials, which are populated by `gcloud auth application-default login`, and then it falls back to trying to directly run gcloud as a subprocess to get a token.

Perhaps it's failing to run gcloud?  Like maybe it's not on the path or something like that?  Are there any messages that would indicate that?  Is it possible for the users to run `gcloud auth print-access-token` from the location the plugin is running?

**Comment by jonjohnsonjr** [comment]
I've also seen this happen when the application default credentials are valid but for a user that doesn't have the right permissions.

**Comment by yihanzhen** [comment]
@sorodrigo can you check if the user having problems installing packages can run `gloud artifacts packages list --repository=<your repo> --location=<location> --project=<project>`? I think this requires the same permission as installing a package from `npm` so that should help locate the issue. It'd also be great if you could paste the result of that and running this auth plugin here.

**Comment by sorodrigo** [comment]
Hello, we managed to solve the issue by:
1. Using `gcloud auth application-defaults login`
2. Making sure the `.npmrc` had a line break between the npm token and the google artifacts stuff.

**Comment by lindsayismith** [comment]
Thanks for updating. Can you give us an example of a file that didn't work, and one that did?  Is the line break something that our tools need to add or is that your own authoring?

**Comment by yihanzhen** [comment]
Closing the issue due to inactivity. Please feel free to ask for reopen or provide additional details of what went wrong. Much appreciated.
