### ISSUE TITLE
support github actions with workload identity federation for google-artifactregistry-auth

### ISSUE THREAD

**Issue by ggprod** [GoogleCloudPlatform/artifact-registry-npm-tools#30]
Though workload identity federation works with github actions.  Currently the google-artifactregistry-auth library does not.  I correctly set up github actions with WIF and authenticated successfully with the google auth action (https://github.com/google-github-actions/auth)... and then tried to run `npx  google-artifactregistry-auth` with no luck.

I also tried setting GOOGLE_APPLICATION_CREDENTIALS to the auth action output credentials_file_path but it still gives the same error:

```
npx: installed 47 in 4.47s
Retrieving application default credentials...
Retrieving credentials from gcloud...
Error: Fail to get credentials. Please run: 
`gcloud auth application-default login`, `gcloud auth login`, or 
`export GOOGLE_APPLICATION_CREDENTIALS=<path/to/service/account/key>`
    at Object.getCreds (/home/runner/.npm/_npx/1616/lib/node_modules/google-artifactregistry-auth/src/auth.js:40:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Which then forces me to forego using workload identity federation and resort to the less secure approach of loading a service account key into a github secret

**Comment by ggprod** [comment]
There is a workaround that can work, but it is ugly... basically in github actions you need to install the gcloud SDK and then run `gcloud auth login --cred-file=${{ steps.auth.outputs.credentials_file_path }}`

**Comment by jonjohnsonjr** [comment]
On a hunch, I would guess this might break workload identity: https://github.com/GoogleCloudPlatform/artifact-registry-npm-tools/blob/9689925a8ca850c999578dbef9a3dd553e7275a2/src/auth.js#L54

@yihanzhen

**Comment by ggprod** [comment]
This turned out to be happening because I was using a too old version of the google auth github action (0.3.1), when I upgraded to the latest version (0.5) it worked without requiring the hack workaround of `gcloud auth login --cred-file=${{ steps.auth.outputs.credentials_file_path }}`
