### ISSUE TITLE
problems with .npmrc

### ISSUE THREAD

**Issue by ggprod** [GoogleCloudPlatform/artifact-registry-npm-tools#31]
When using google-artifactregistry-auth if you try to run with the --credential-config option and a local/project .npmrc file that doesn't have the _authToken property you get `Error: Artifact Registry config not found in /path/to/.npmrc`

Normally we'd like to store the _authToken in the user .npmrc file for development purposes but we need to store it in the project/local .npmrc when building containers (because the user .npmrc will not be available in the container image)

We'd like to be able to keep our local/project .npmrc without the _authToken so that it can be stored and used from the user .npmrc but then we can't properly authenticate when building containers because of the above error which forces us to keep our local/project .npmrc file with the _authToken="" line so that we can use the --credential-config option

This is a request to update the script so that it can populate the _authToken into the local/project .npmrc file via the --credntial-config option even if it isn't present before running the command

**Comment by ggprod** [comment]
as a specific example, when we run `npx google-artifactregistry-auth --credntial-config=.npmrc` in a folder and there is an .npmrc file in the folder that looks like
```
@xyz:registry=https://us-npm.pkg.dev/tealbook-shared/npm/
//us-npm.pkg.dev/xyz/abc/:_authToken=""
//us-npm.pkg.dev/xyz/abc/:always-auth=true
```

it works fine.. however if the instead the .npmrc looks like

```
@tealbook:registry=https://us-npm.pkg.dev/tealbook-shared/npm/
//us-npm.pkg.dev/tealbook-shared/npm/:always-auth=true
```

we get the error `Error: Artifact Registry config not found in /path/to/.npmrc`.. This is a request to fix it so the second form works and simply adds in the `//us-npm.pkg.dev/xyz/abc/:_authToken="token"`

**Comment by lindsayismith** [comment]
+Hanzhen Yi ***@***.***>

**Comment by yihanzhen** [comment]
@ggprod thanks for the report! This is indeed a bug in the plugin. I'll put together a fix probably in the coming weeks.

Also if you have the time and interest a pull request would be much appreciated :)

**Comment by ggprod** [comment]
@yihanzhen I finally got some time to look into fixing this issue, PR submitted

**Comment by RezaRahmati** [comment]
> as a specific example, when we run `npx google-artifactregistry-auth --credntial-config=.npmrc` in a folder and there is an .npmrc file in the folder that looks like
> 
> ```
> @xyz:registry=https://us-npm.pkg.dev/tealbook-shared/npm/
> //us-npm.pkg.dev/xyz/abc/:_authToken=""
> //us-npm.pkg.dev/xyz/abc/:always-auth=true
> ```
> 
> it works fine and populates the token string into the _authToken property.. however if the instead the .npmrc looks like
> 
> ```
> @xyz:registry=https://us-npm.pkg.dev/xyz/abc/
> //us-npm.pkg.dev/xyz/abc/:always-auth=true
> ```
> 
> we get the error `Error: Artifact Registry config not found in /path/to/.npmrc`.. This is a request to fix it so the second form works and simply adds in the `//us-npm.pkg.dev/xyz/abc/:_authToken="token-string"`... This is already what it does for the user .npmrc file (it will add the `//us-npm.pkg.dev/xyz/abc/:_authToken="token-string"` even if the user .npmrc file was previously empty

there is a typo in `credential-config` , I copy pasted and spend hours until I figured it out , would be great if you can edit yours and fix the typo

**Comment by yihanzhen** [comment]
@RezaRahmati Can you be more specific? The pull request from @ggprod has been submitted long time ago so I'm not quite sure what problem you are running into.

**Comment by RezaRahmati** [comment]
> @RezaRahmati Can you be more specific? The pull request from @ggprod has been submitted long time ago so I'm not quite sure what problem you are running into.

There is a typo in the first line of your message

**Comment by yihanzhen** [comment]
Oh gotcha, thanks. I have just updated it.
