### ISSUE TITLE
Scopes containing dots break the functionality

### ISSUE THREAD

**Issue by tom-b-wright** [GoogleCloudPlatform/artifact-registry-npm-tools#37]
Npm scope names can contain dots in the middle as they should follow package naming rules.
"package name should not start with . or _"

If we set a scope with a dot, then the login function removes the scope from .npmrc and that breaks installing other packages.

To fix this you need to add dot in the regex that deals with scopes.

**Comment by yihanzhen** [comment]
@tom-b-wright Would you be willing to send us a pull request?
