### ISSUE TITLE
auth to artifact registry broken when using service account

### ISSUE THREAD

**Issue by devops-braininance** [GoogleCloudPlatform/artifact-registry-npm-tools#58]
Hi,

We use cloud build to build our app with private dependencies, everything worked fined with this .npmrc 

```
@project:registry=https://northamerica-northeast1-npm.pkg.dev/project/npm-registry/
//northamerica-northeast1-npm.pkg.dev/project/npm-registry/:_password=""
//northamerica-northeast1-npm.pkg.dev/project/npm-registry/:username=oauth2accesstoken
//northamerica-northeast1-npm.pkg.dev/project/npm-registry/:email=not.valid@email.com
//northamerica-northeast1-npm.pkg.dev/project/npm-registry/:always-auth=true
```

However, it stopped working today on Cloud Build, locally, it works fine. After some debugging, we had to delete the line below to make it work.

```
//northamerica-northeast1-npm.pkg.dev/project/npm-registry/:_password=""
```

npx google-artifactregistry-auth --repo-config=.npmrc --credential-config=.npmrc will automatically generate the auth line.

//northamerica-northeast1-npm.pkg.dev/project/npm-registry/:_authToken=""

What was the update that changed this behavior? And what's the difference between _authToken and _password?

**Comment by devops-braininance** [comment]
Edit found this: https://github.com/npm/npm/issues/9866
It came into effect today?

**Comment by lindsayismith** [comment]
Hanzhen did something change with this?

**Comment by yihanzhen** [comment]
This is probably https://github.com/GoogleCloudPlatform/artifact-registry-npm-tools/pull/56 which broke the backward compatibility on supporting specifying the auth token through `_password`. I'll do some more digging.

**Comment by yihanzhen** [comment]
@devops-braininance we will probably publish a newer version reverting this behavior change, and I think it might be better that you pin your auth plugin to a version. It seems you have gotten it to work by removing the password line. If you are happy with it, pin to `3.1.2`. If you want the old behavior back, pin to `3.1.1` and wait for `3.1.3`.

To pin to a specific version, do this:

```
npx google-artifactregistry-auth@3.1.2 --repo-config=.npmrc --credential-config=.npmrc
```

**Comment by devops-braininance** [comment]
Thank you for the advice !
