### ISSUE TITLE
Using Artifact registry in Continuous Integration

### ISSUE THREAD

**Issue by Algirdyz** [GoogleCloudPlatform/artifact-registry-npm-tools#6]
Is there a preferred way of using the artifact registry in CI environments?
Right now it seems, that the only way to authenticate is to get 1h long token, which is a bit awkward to use in, for example, github actions.

Are there any plans to get a permanent token to save as a secret for example? Or is there a flow you think is better?

**Comment by KaylaNguyen** [comment]
We now support service account credentials in npm configuration which I believe would work for CI flow: https://cloud.devsite.corp.google.com/artifact-registry/docs/nodejs/authentication#auth-password
Please let me know if you have any question. Thanks! :)

**Comment by lindsayismith** [comment]
We fully appreciate that the 1hr tokens are a pain point with Npm, as it does not have any auth hooks that would allow a new token to be generated automatically when required.

For headless CI systems, another option is to use a service account, and to use the JSON key for the SA to authenticate.  Some notes on this are here:

https://cloud.google.com/artifact-registry/docs/nodejs/authentication#auth-password
